services:
  cluster:
    image: valkey/valkey:8.0-alpine
    entrypoint:
      - /bin/sh
      - -c
      - |
        valkey-server --port 7001 --save "" --appendonly no --cluster-enabled yes --cluster-config-file 7001.conf &
        valkey-server --port 7002 --save "" --appendonly no --cluster-enabled yes --cluster-config-file 7002.conf &
        valkey-server --port 7003 --save "" --appendonly no --cluster-enabled yes --cluster-config-file 7003.conf &
        valkey-server --port 7021 --save "" --appendonly no --cluster-enabled yes --cluster-config-file 7021.conf &
        valkey-server --port 7022 --save "" --appendonly no --cluster-enabled yes --cluster-config-file 7022.conf &
        valkey-server --port 7023 --save "" --appendonly no --cluster-enabled yes --cluster-config-file 7023.conf &
        while ! valkey-cli --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7021 127.0.0.1:7022 127.0.0.1:7023 --cluster-replicas 1 --cluster-yes; do sleep 1; done
        wait
    ports:
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7021:7021"
      - "7022:7022"
      - "7023:7023"

